### ISSUE TITLE
save/load the world

### ISSUE THREAD

**Issue by rom1504** [dazed-sheep/dazed-sheep#1]
Should be easy enough to do with https://github.com/mhsjlw/minecraft-classic-anvil

- [x] loading
- [x] saving

**Comment by mhsjlw** [comment]
It gives us a buffer of blocks, how can we split that up so we can send it to the user?

**Comment by rom1504** [comment]
@mhsjlw how big is the buffer ?

**Comment by mhsjlw** [comment]
When running the read.js example in the repo based off of a world generated by the official minecraft server and running `console.log(data.blocks.$.length);`, it is `4194304`

**Comment by rom1504** [comment]
console.log(data["blocks"]["$"].length)

4194304

= 256*64*256

so it's exactly the same format

make a load in world.js that does this.data=data; and done.

**Comment by rom1504** [comment]
hmm, not exactly this.data=data;
actually data.copy(this.data,4);

**Comment by rom1504** [comment]
well might as well include the require('minecraft-classic-anvil') and usage directly in world.js ;)

**Comment by mhsjlw** [comment]
I need to publish it then... should we implement world writing first? Like setting blocks? Or should I just disable that for now, so you can only read?

**Comment by rom1504** [comment]
@mhsjlw I think, just remove x,y, z and block in https://github.com/mhsjlw/minecraft-classic-anvil/blob/master/src/write.js and it's done.

I mean it'll be enough to use it.

**Comment by rom1504** [comment]
ah nevermind, you just copy pasted this from read.js, there's some stuff to change indeed.

But just implement as "encode in that java.io format and let the user handle the format" I think, for now.

**Comment by rom1504** [comment]
But anyway yeah, publishing it with just load working is okay.

**Comment by mhsjlw** [comment]
Ok. before I push though I am adding a readSync function in case we need it

**Comment by rom1504** [comment]
I don't think it's needed to have a readSync no.

**Comment by mhsjlw** [comment]
it's done I just need to add a /save command
