### ISSUE TITLE
extended classic protocol

### ISSUE THREAD

**Issue by mhsjlw** [dazed-sheep/dazed-sheep#5]
add support for the extended protocol. requires some changes in minecraft-classic-protocol http://wiki.vg/Classic_Protocol_Extension

**Comment by rom1504** [comment]
see https://github.com/mhsjlw/minecraft-classic-protocol/issues/5

**Comment by mhsjlw** [comment]
https://github.com/dazed-sheep/dazed-sheep/commit/244123a30a9ee31b00a6ca7890ad95c996da918b and https://github.com/mhsjlw/minecraft-classic-protocol-extension now all we need is to individually implement each feature
